// <auto-generated />
using System;
using Calender.DBAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Calender.Migrations
{
    [DbContext(typeof(DBAccessContext))]
    partial class DBAccessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Calender.Models.TaskInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("taskContents")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("taskDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("taskName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("DBAccess");
                });
#pragma warning restore 612, 618
        }
    }
}
